sudo: required
services:
  - docker

build:
  - docker build -t mpayancabrera/docker-react -f Dockerfile.dev .

script:
  - docker run mpayancabrera/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-902137919815"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

